services:
  nemoclaw:
    container_name: nemoclaw
    image: shmayro/nemoclaw
    build: .
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - nemoclaw-data:/nemoclaw-data
    environment:
      - NVIDIA_API_KEY=${NVIDIA_API_KEY:-}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - SKIP_ONBOARD=${SKIP_ONBOARD:-}
      - TTYD_USER=${TTYD_USER:-}
      - TTYD_PASS=${TTYD_PASS:-}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
      - SANDBOX_NAME=${SANDBOX_NAME:-my-assistant}
      - ALLOWED_CHAT_IDS=${ALLOWED_CHAT_IDS:-}

volumes:
  nemoclaw-data:
